In [1]:
# import libraries
import numpy as np
import torch

# Using Numpy

In [8]:
# create some random matrices

A = np.random.randn(3,4)
B = np.random.randn(4,5)
C = np.random.randn(3,7)

# try some multiplications
#print(np.round(A@B, 2)), print(' ')
#print(np.round(A@C , 2)), print(' ')
#print(np.round(B@C , 2)), print(' ')
print(np.round(C.T@A , 2))

[[-1.92 -0.04 -0.35 -1.18]
 [ 1.48  2.65 -0.77  2.04]
 [-1.8   0.53 -0.57 -0.84]
 [ 0.81 -1.33  0.53  0.02]
 [-1.12 -0.99 -0.84 -0.38]
 [-1.85  0.12 -0.34 -1.11]
 [-1.27  0.55  1.32 -1.77]]


# Using Pytorch

In [10]:
# create some random matrices

A = torch.randn(3,4)
B = torch.randn(4,5)
C1 = np.random.randn(4,7)
C2 = torch.tensor(C1, dtype= torch.float)


# try some multiplication
# print(np.round( A@B   ,2)), print(' ')
# print(np.round( A@B.T ,2)), print(' ')
print(np.round( A@C1  ,2)), print(' ')
print(np.round( A@C2  ,2))

tensor([[-1.4100, -2.2600, -0.4300,  2.4100,  4.9200, -0.6400,  1.1900],
        [ 0.2800, -0.4200, -0.5100,  0.6300, -0.1800, -0.5000,  0.2800],
        [-1.8000, -1.3700, -0.3800, -0.5600, -3.3100,  1.8500,  0.1300]],
       dtype=torch.float64)
 
tensor([[-1.4100, -2.2600, -0.4300,  2.4100,  4.9200, -0.6400,  1.1900],
        [ 0.2800, -0.4200, -0.5100,  0.6300, -0.1800, -0.5000,  0.2800],
        [-1.8000, -1.3700, -0.3800, -0.5600, -3.3100,  1.8500,  0.1300]])
