In [1]:
#import libraries
import numpy as np
import torch


In [3]:
# generate a few random numbers
np.random.randn(5)


array([-1.17309001, -0.27120642, -0.13228323,  1.32887359,  1.42191384])

In [6]:
# repeat after fixing the seed (old-but-still widely used method)
np.random.seed(17)
print(np.random.randn(5))
print(np.random.randn(5))


#[ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
#[ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]

[ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
[ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]


# New seed mechanism in numpy

In [8]:
randseed1 = np.random.RandomState(17)
randseed2 = np.random.RandomState(5687557)


print( randseed1.randn(5) ) 
print( randseed2.randn(5) ) 
print( randseed1.randn(5) ) 
print( randseed2.randn(5) ) 
print( np.random.randn(5) )

[ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
[ 1.40545635  0.31980704  2.44752776 -0.94798335 -0.5992708 ]
[ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]
[-0.57247557  0.40403186 -1.57966438  1.64245159 -0.68470715]
[ 2.171257    1.15231025 -1.81881234 -0.13804934  0.53983961]


## Now in Pytorch

In [9]:
torch.randn(5)


tensor([-0.2574,  0.2867, -0.5182,  0.2448,  1.5637])

In [11]:
torch.manual_seed(17)
print(torch.randn(5))

# torch's seed doesn't spread to numpy
print( np.random.randn(5) )

tensor([-1.4135,  0.2336,  0.0340,  0.3499, -0.0145])
[-0.9822943   1.03126909  0.49133378 -0.4466466  -0.80636008]
