In [11]:
#import libraries
import torch
import torch.nn as nn
import torch.nn.functional as F

# using dropout

In [12]:
#define a dropout instance and make some data
prob = .5

dropout = nn.Dropout(p=prob)
x = torch.ones(10)

#lets see whats dropout returns

y = dropout(x)
print(x)
print(y*(1-prob))
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([0., 0., 1., 1., 1., 1., 0., 1., 1., 1.])
tensor(1.4000)


In [13]:
#dropout is turned off when evaluating the model

dropout.eval()
y = dropout(x)
print(y)
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor(1.)


In [14]:
#annoyingly, F.dropout() is not de activated in eval model

dropout.eval()
y = F.dropout(x)
print(y)
print(torch.mean(y))


tensor([2., 2., 2., 2., 0., 0., 2., 0., 0., 2.])
tensor(1.2000)


In [15]:
#but you can manually switch it off.
#dropout.eval()

y = F.dropout(x, training=False)

print(y)
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor(1.)


In [17]:
#the model needs to be reset after toggling into eval mode

dropout.train()
y = dropout(x)
print(y) #with dropout

dropout.eval()
y = dropout(x)
print(y) #without dropout


# dropout.train()
y = dropout(x)
print(y) # still w/o dropout ;)

tensor([0., 2., 0., 2., 0., 2., 2., 0., 2., 2.])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
